// discovery.js
//
// Spotify-style discovery features for JaySoundCloud.
//
// Songs live in the third-party SoundCloud proxy, not in your DB — so this
// module keeps a lightweight local CACHE of track metadata (title, artist,
// thumbnail, url, duration, plays) any time a track is searched or played.
// That cache is what powers "popular artists", "trending", and the
// recommendation fallbacks. It is NOT a source of truth for playback —
// just enough metadata to rank and relate tracks.
//
// Field shape matches what /api/search/soundcloud already returns and what
// public/index.html already expects: track_id, title, artist, duration,
// plays, url, thumbnail. `url` is the SoundCloud permalink and is treated
// as the stable identifier where track_id is missing.
//
// New tables required (add to your Supabase SQL setup):
//
//   create table tracks_cache (
//     track_id text primary key,
//     title text not null,
//     artist text not null,
//     duration text,
//     thumbnail text,
//     url text,
//     first_seen_at timestamptz default now(),
//     last_seen_at timestamptz default now()
//   );
//
//   create table play_events (
//     id bigint generated by default as identity primary key,
//     track_id text not null,
//     played_at timestamptz default now()
//   );
//
//   create index play_events_track_id_idx on play_events (track_id);
//   create index play_events_played_at_idx on play_events (played_at);
//
// Wire-up (already done in index.js):
//   - upsertManyTrackCache() runs after every /api/search/soundcloud call
//   - upsertTrackCache() + logPlay() run on POST /api/discovery/log-play,
//     which the frontend calls from streamAndPlayTrack()

// ---------------------------------------------------------------------------
// 0a. Cache track metadata (call on search results + on play)
// ---------------------------------------------------------------------------
function normalizeId(track) {
    return String(track.track_id || track.url || '').trim();
}

async function upsertTrackCache(supabase, track) {
    const track_id = normalizeId(track);
    if (!track_id) return;
    const { error } = await supabase
        .from('tracks_cache')
        .upsert(
            {
                track_id,
                title: track.title || 'Unknown title',
                artist: track.artist || 'Unknown artist',
                duration: track.duration || null,
                thumbnail: track.thumbnail || null,
                url: track.url || null,
                last_seen_at: new Date().toISOString(),
            },
            { onConflict: 'track_id' }
        );
    if (error) console.error('upsertTrackCache error:', error.message);
}

async function upsertManyTrackCache(supabase, tracks) {
    if (!Array.isArray(tracks) || !tracks.length) return;
    const rows = tracks
        .map(t => ({ ...t, track_id: normalizeId(t) }))
        .filter(t => t.track_id)
        .map(t => ({
            track_id: t.track_id,
            title: t.title || 'Unknown title',
            artist: t.artist || 'Unknown artist',
            duration: t.duration || null,
            thumbnail: t.thumbnail || null,
            url: t.url || null,
            last_seen_at: new Date().toISOString(),
        }));
    if (!rows.length) return;
    const { error } = await supabase.from('tracks_cache').upsert(rows, { onConflict: 'track_id' });
    if (error) console.error('upsertManyTrackCache error:', error.message);
}

// ---------------------------------------------------------------------------
// 0b. Log a play event (call this from the frontend when a track starts)
// ---------------------------------------------------------------------------
async function logPlay(supabase, trackId) {
    if (!trackId) return;
    const { error } = await supabase.from('play_events').insert({ track_id: trackId });
    if (error) console.error('logPlay error:', error.message);
}

// ---------------------------------------------------------------------------
// 1. Trending songs — velocity based (recent plays weighted over older plays)
// ---------------------------------------------------------------------------
async function getTrendingTracks(supabase, limit = 20) {
    const now = new Date();
    const h48 = new Date(now - 48 * 60 * 60 * 1000).toISOString();
    const h96 = new Date(now - 96 * 60 * 60 * 1000).toISOString();

    const { data: recent, error: e1 } = await supabase
        .from('play_events')
        .select('track_id')
        .gte('played_at', h48);

    const { data: prior, error: e2 } = await supabase
        .from('play_events')
        .select('track_id')
        .gte('played_at', h96)
        .lt('played_at', h48);

    if (e1 || e2) {
        console.error('getTrendingTracks error:', e1?.message, e2?.message);
        return [];
    }

    const recentCounts = countBy(recent, 'track_id');
    const priorCounts = countBy(prior, 'track_id');

    const scored = Object.keys(recentCounts)
        .map(trackId => ({
            track_id: trackId,
            score: recentCounts[trackId] * 2 - (priorCounts[trackId] || 0),
        }))
        .sort((a, b) => b.score - a.score)
        .slice(0, limit);

    return hydrateWithTrackInfo(supabase, scored);
}

// ---------------------------------------------------------------------------
// 2. Popular artists — aggregate plays (from play_events) by cached artist
// ---------------------------------------------------------------------------
async function getPopularArtists(supabase, limit = 20) {
    const { data: plays, error: e1 } = await supabase
        .from('play_events')
        .select('track_id');

    if (e1) {
        console.error('getPopularArtists error:', e1.message);
        return [];
    }
    if (!plays?.length) return [];

    const playCounts = countBy(plays, 'track_id');
    const trackIds = Object.keys(playCounts);

    const { data: cached, error: e2 } = await supabase
        .from('tracks_cache')
        .select('track_id, artist')
        .in('track_id', trackIds);

    if (e2) {
        console.error('getPopularArtists cache lookup error:', e2.message);
        return [];
    }

    const totals = {};
    for (const row of cached || []) {
        const plays = playCounts[row.track_id] || 0;
        totals[row.artist] = (totals[row.artist] || 0) + plays;
    }

    return Object.entries(totals)
        .map(([artist, totalPlays]) => ({ artist, totalPlays }))
        .sort((a, b) => b.totalPlays - a.totalPlays)
        .slice(0, limit);
}

// ---------------------------------------------------------------------------
// 3. Recommendations for a seed track — co-occurrence, then fallbacks
// ---------------------------------------------------------------------------
async function getRecommendations(supabase, seedTrackId, limit = 10) {
    let recs = [];

    // 3a. Collaborative filtering via liked_songs co-occurrence.
    // liked_songs is keyed by url (see README schema), so seedTrackId is
    // expected to be a track's url/track_id (same value, per normalizeId).
    const { data: coUsers, error: e1 } = await supabase
        .from('liked_songs')
        .select('user_id')
        .eq('url', seedTrackId);

    if (!e1 && coUsers?.length) {
        const userIds = coUsers.map(r => r.user_id);
        const { data: coLiked, error: e2 } = await supabase
            .from('liked_songs')
            .select('track_id, title, artist, thumbnail, url, duration')
            .in('user_id', userIds)
            .neq('url', seedTrackId);

        if (!e2 && coLiked?.length) {
            const counts = {};
            for (const row of coLiked) {
                const key = row.url;
                counts[key] = counts[key] || { ...row, track_id: row.url, count: 0 };
                counts[key].count += 1;
            }
            recs = Object.values(counts).sort((a, b) => b.count - a.count);
        }
    }

    if (recs.length >= limit) return recs.slice(0, limit);

    // Need seed's own metadata for the fallbacks below
    const { data: seed } = await supabase
        .from('tracks_cache')
        .select('artist, title')
        .eq('track_id', seedTrackId)
        .single();

    // 3b. Fallback: same artist, most played
    if (seed?.artist) {
        const { data: sameArtistCache } = await supabase
            .from('tracks_cache')
            .select('track_id, title, artist, thumbnail, url, duration')
            .eq('artist', seed.artist)
            .neq('track_id', seedTrackId)
            .limit(limit * 2); // over-fetch, we'll rank by plays next

        if (sameArtistCache?.length) {
            const ranked = await rankByPlays(supabase, sameArtistCache);
            recs = dedupeByTrackId([...recs, ...ranked]);
        }
    }

    if (recs.length >= limit || !seed?.title) return recs.slice(0, limit);

    // 3c. Fallback: keyword overlap in title (crude genre/mood proxy)
    const keywords = seed.title
        .toLowerCase()
        .split(/\s+/)
        .filter(w => w.length > 3)
        .slice(0, 3);

    for (const kw of keywords) {
        const { data: kwMatches } = await supabase
            .from('tracks_cache')
            .select('track_id, title, artist, thumbnail, url, duration')
            .ilike('title', `%${kw}%`)
            .neq('track_id', seedTrackId)
            .limit(limit);

        if (kwMatches?.length) {
            recs = dedupeByTrackId([...recs, ...kwMatches]);
        }
        if (recs.length >= limit) break;
    }

    return recs.slice(0, limit);
}

// ---------------------------------------------------------------------------
// 4. Radio queue — blends recommendations with trending for broader variety
// ---------------------------------------------------------------------------
async function generateRadioQueue(supabase, seedTrackId, queueLength = 30) {
    const [similar, trending] = await Promise.all([
        getRecommendations(supabase, seedTrackId, Math.ceil(queueLength * 0.6)),
        getTrendingTracks(supabase, Math.ceil(queueLength * 0.4)),
    ]);

    const pool = dedupeByTrackId([...similar, ...trending]);
    return shuffle(pool).slice(0, queueLength);
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------
function countBy(rows, key) {
    const counts = {};
    for (const row of rows || []) {
        counts[row[key]] = (counts[row[key]] || 0) + 1;
    }
    return counts;
}

function dedupeByTrackId(rows) {
    const seen = new Set();
    const out = [];
    for (const row of rows) {
        if (row?.track_id && !seen.has(row.track_id)) {
            seen.add(row.track_id);
            out.push(row);
        }
    }
    return out;
}

function shuffle(arr) {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
}

// attach cached title/artist/thumbnail/url to a list of { track_id, score }
async function hydrateWithTrackInfo(supabase, scoredList) {
    if (!scoredList.length) return [];
    const ids = scoredList.map(s => s.track_id);
    const { data: cached, error } = await supabase
        .from('tracks_cache')
        .select('track_id, title, artist, thumbnail, url, duration')
        .in('track_id', ids);

    if (error) {
        console.error('hydrateWithTrackInfo error:', error.message);
        return scoredList;
    }

    const byId = Object.fromEntries((cached || []).map(c => [c.track_id, c]));
    return scoredList.map(s => ({ ...s, ...byId[s.track_id] }));
}

// rank a list of cached tracks by their play_events count, descending
async function rankByPlays(supabase, cachedTracks) {
    const ids = cachedTracks.map(t => t.track_id);
    const { data: plays, error } = await supabase
        .from('play_events')
        .select('track_id')
        .in('track_id', ids);

    if (error) {
        console.error('rankByPlays error:', error.message);
        return cachedTracks;
    }

    const counts = countBy(plays, 'track_id');
    return [...cachedTracks].sort((a, b) => (counts[b.track_id] || 0) - (counts[a.track_id] || 0));
}

module.exports = {
    normalizeId,
    upsertTrackCache,
    upsertManyTrackCache,
    logPlay,
    getTrendingTracks,
    getPopularArtists,
    getRecommendations,
    generateRadioQueue,
};
